Improve PE File & Program Icon Loading
Whisky-App/Whisky pull request #670
Opened 2023-12-01 18:52 UTC by divadretlaw

## PEFile Improvements

- Close `FileHandle` after parsing
- Split types into multiple files
- Add some documentation
- Fix `OptionalHeader` not differentiating PE32 and PE32+
- Interpret more values while parsing (maybe a bit overkill, but they could be useful in the future or other projects trying to access values of a PE file)
- Improve Icon Loading

I think it would be best to cache the icons as it seems to take a bit to load them to find the best / largest one.

I would recommend https://github.com/kean/Nuke but there are many options and even the possibility to create a cache without any dependencies if that is desired.

Adding a dependency should be the decision of the maintainer and if they think adding a cache, and also which library to use if any, then I would be happy to implement that as well.

2023-12-02 06:59 UTC, JoshuaBrest commented
What do you mean by cache?

2023-12-04 17:48 UTC, IsaacMarovitz commented
Most of the improvements to PE parsing that I'm seeing here are not relevant. The parsing implementation used was designed to be a bit naive, as we really only need the data present in the resource table for our purposes. If we wanted to create a more complete implementation, as is shown here, it might be worth splitting it into a separate project/swift package.

2023-12-04 23:49 UTC, divadretlaw commented
That approach makes sense, I reverted the not-needed changes to the PE parsing

2023-12-08 15:24 UTC, IsaacMarovitz requested changes

2023-12-08 15:24 UTC, IsaacMarovitz commented on WhiskyKit/Sources/WhiskyKit/Extensions/FileHandle+Extensions.swift
> +    func extract<T>(_ type: T.Type, offset: UInt64 = 0) -> T? {
Is the `Data` extract extension still used? If not I'd remove it.

2023-12-08 15:24 UTC, IsaacMarovitz commented on Whisky/Views/Bottle/Pins/PinView.swift
> +            let task = Task<Image?, Never>.detached {
Would removing `@MainActor` here not be sufficient? This seems a little verbose.

2023-12-08 15:40 UTC, IsaacMarovitz commented on WhiskyKit/Sources/WhiskyKit/PE/PortableExecutable.swift
> +    #if canImport(AppKit)
https://developer.apple.com/documentation/coregraphics/cgcontext/1455939-init

2024-01-12 16:49 UTC, IsaacMarovitz approved these changes

2024-01-12 16:50 UTC, merged